// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, author_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, author_id, parent_id, content, created_at
`

type CreateCommentParams struct {
	PostID   int64       `json:"post_id"`
	AuthorID int64       `json:"author_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Content  string      `json:"content"`
}

// parent_id is NULL for a top-level comment, or another comment's id for a reply.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments
WHERE id = $1 AND author_id = $2
RETURNING id
`

type DeleteCommentParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

// Owner-only. Cascade removes the comment's whole reply subtree.
// RETURNING tells us if a row was actually deleted (else ErrNoRows → 404).
func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteComment, arg.ID, arg.AuthorID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCommentTree = `-- name: GetCommentTree :many
WITH RECURSIVE thread AS (
    -- ANCHOR: top-level comments (no parent) on this post.
    SELECT c.id, c.post_id, c.author_id, c.parent_id, c.content, c.created_at,
           1 AS depth,
           ARRAY[c.id] AS path
    FROM comments c
    WHERE c.post_id = $1 AND c.parent_id IS NULL

    UNION ALL

    -- RECURSIVE: replies to comments we've already collected. Repeats until
    -- no new replies are found. depth +1 per level; path appends this id so we
    -- can order the result depth-first (each reply sits under its parent).
    SELECT c.id, c.post_id, c.author_id, c.parent_id, c.content, c.created_at,
           t.depth + 1,
           t.path || c.id
    FROM comments c
    JOIN thread t ON c.parent_id = t.id
)
SELECT id, post_id, author_id, parent_id, content, created_at, depth
FROM thread
ORDER BY path
`

type GetCommentTreeRow struct {
	ID        int64              `json:"id"`
	PostID    int64              `json:"post_id"`
	AuthorID  int64              `json:"author_id"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Depth     int32              `json:"depth"`
}

// Fetch a post's ENTIRE comment tree (all nesting levels) with a recursive CTE.
func (q *Queries) GetCommentTree(ctx context.Context, postID int64) ([]GetCommentTreeRow, error) {
	rows, err := q.db.Query(ctx, getCommentTree, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentTreeRow{}
	for rows.Next() {
		var i GetCommentTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
