// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package sqlc

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const findNearDuplicates = `-- name: FindNearDuplicates :many
WITH target AS (
    SELECT embedding FROM post_embeddings WHERE post_id = $1
)
SELECT p.id, p.author_id, p.content,
       (e.embedding <=> (SELECT embedding FROM target))::float8 AS distance
FROM posts p
JOIN post_embeddings e ON e.post_id = p.id
WHERE p.id != $1
  AND (e.embedding <=> (SELECT embedding FROM target)) < $2::float8
ORDER BY distance
LIMIT $3
`

type FindNearDuplicatesParams struct {
	PostID      int64   `json:"post_id"`
	MaxDistance float64 `json:"max_distance"`
	ResultLimit int32   `json:"result_limit"`
}

type FindNearDuplicatesRow struct {
	ID       int64   `json:"id"`
	AuthorID int64   `json:"author_id"`
	Content  string  `json:"content"`
	Distance float64 `json:"distance"`
}

// Near-duplicate / astroturf detection. Returns every OTHER post whose embedding
// is within a cosine DISTANCE THRESHOLD of the given post. Unlike GetRelatedPosts
// (which returns the top-N nearest, always something), this uses an ABSOLUTE
// threshold — the threshold itself is the definition of "is this a copy?". Posts
// below it are near-identical in meaning even if the words were shuffled.
func (q *Queries) FindNearDuplicates(ctx context.Context, arg FindNearDuplicatesParams) ([]FindNearDuplicatesRow, error) {
	rows, err := q.db.Query(ctx, findNearDuplicates, arg.PostID, arg.MaxDistance, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearDuplicatesRow{}
	for rows.Next() {
		var i FindNearDuplicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelatedPosts = `-- name: GetRelatedPosts :many
SELECT p.id, p.author_id, p.content, p.created_at
FROM posts p
JOIN post_embeddings e ON e.post_id = p.id
WHERE p.id != $1
ORDER BY e.embedding <=> (SELECT embedding FROM post_embeddings WHERE post_id = $1)
LIMIT $2
`

type GetRelatedPostsParams struct {
	PostID      int64 `json:"post_id"`
	ResultLimit int32 `json:"result_limit"`
}

// "More like this": find posts nearest to a GIVEN post's own embedding,
// excluding that post itself. The subquery fetches the target post's vector.
func (q *Queries) GetRelatedPosts(ctx context.Context, arg GetRelatedPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getRelatedPosts, arg.PostID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const keywordCandidates = `-- name: KeywordCandidates :many
SELECT id, author_id, content, created_at
FROM posts
WHERE to_tsvector('english', content) @@ websearch_to_tsquery('english', $1)
ORDER BY ts_rank(to_tsvector('english', content), websearch_to_tsquery('english', $1)) DESC
LIMIT $2
`

type KeywordCandidatesParams struct {
	Query       string `json:"query"`
	ResultLimit int32  `json:"result_limit"`
}

// KEYWORD arm of hybrid search: exact-term (full-text) matching, ranked by
// ts_rank. Catches proper nouns / rare jargon (library names, error codes,
// usernames) that the embedding model blurs away.
// websearch_to_tsquery parses raw user input safely (quotes, OR, -negation) and
// never throws on weird syntax. It uses the same to_tsvector expression as the
// GIN index, so the WHERE clause is index-accelerated.
func (q *Queries) KeywordCandidates(ctx context.Context, arg KeywordCandidatesParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, keywordCandidates, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByEmbedding = `-- name: SearchPostsByEmbedding :many
SELECT id, author_id, content, created_at
FROM (
    SELECT
        p.id, p.author_id, p.content, p.created_at,
        (1 - (e.embedding <=> $1::vector)) AS relevance
    FROM posts p
    JOIN post_embeddings e ON e.post_id = p.id
    ORDER BY e.embedding <=> $1::vector -- HNSW-accelerated
    LIMIT 100 -- candidate pool to re-rank
) AS candidates
ORDER BY
    relevance
    * EXP(-EXTRACT(EPOCH FROM (NOW() - created_at)) / 604800.0)        -- recency: ~1-week decay
    * (1 + LN(1 + (SELECT COUNT(*) FROM likes l
                   WHERE l.post_id = candidates.id)))                   -- engagement (REAL likes)
    DESC
LIMIT $2
`

type SearchPostsByEmbeddingParams struct {
	QueryEmbedding pgvector.Vector `json:"query_embedding"`
	ResultLimit    int32           `json:"result_limit"`
}

// TWO-STAGE search: relevance is NOT the same as quality, so we don't just
// return "most on-topic" — we return "on-topic AND fresh AND from someone with reach".
//
//	Stage 1 (inner): HNSW fetches the nearest ~100 candidates by PURE cosine
//	                 distance — fast, index-accelerated.
//	Stage 2 (outer): re-rank ONLY those candidates by a blended score:
//	                 relevance × recency-decay × author-authority.
func (q *Queries) SearchPostsByEmbedding(ctx context.Context, arg SearchPostsByEmbeddingParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, searchPostsByEmbedding, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const semanticCandidates = `-- name: SemanticCandidates :many
SELECT p.id, p.author_id, p.content, p.created_at
FROM posts p
JOIN post_embeddings e ON e.post_id = p.id
ORDER BY e.embedding <=> $1::vector
LIMIT $2
`

type SemanticCandidatesParams struct {
	QueryEmbedding pgvector.Vector `json:"query_embedding"`
	ResultLimit    int32           `json:"result_limit"`
}

// SEMANTIC arm of hybrid search: PURE nearest-neighbour by meaning (cosine),
// with NO recency/engagement re-rank. RRF fuses raw RANKS, so each arm must be
// a clean ranked list — mixing quality signals in here would muddy the fusion.
// HNSW-accelerated, same as the semantic /search path.
func (q *Queries) SemanticCandidates(ctx context.Context, arg SemanticCandidatesParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, semanticCandidates, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPostEmbedding = `-- name: UpsertPostEmbedding :exec
INSERT INTO post_embeddings (post_id, embedding)
VALUES ($1, $2::vector)
ON CONFLICT (post_id) DO UPDATE SET embedding = EXCLUDED.embedding
`

type UpsertPostEmbeddingParams struct {
	PostID    int64           `json:"post_id"`
	Embedding pgvector.Vector `json:"embedding"`
}

// Store (or replace) a post's embedding. Upsert so re-processing the same post
// (at-least-once delivery from the queue) just overwrites — idempotent.
func (q *Queries) UpsertPostEmbedding(ctx context.Context, arg UpsertPostEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertPostEmbedding, arg.PostID, arg.Embedding)
	return err
}
