// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fanOutPostToFollowers = `-- name: FanOutPostToFollowers :exec
INSERT INTO timelines (user_id, post_id)
SELECT f.follower_id, $1
FROM follows f
WHERE f.followee_id = $2
ON CONFLICT (user_id, post_id) DO NOTHING
`

type FanOutPostToFollowersParams struct {
	PostID   int64 `json:"post_id"`
	AuthorID int64 `json:"author_id"`
}

// Fan-out-on-WRITE: push a freshly-created post into the precomputed timeline
// of every follower of its author. INSERT ... SELECT writes one row per
// follower in a single statement. ON CONFLICT DO NOTHING = idempotent.
// (Skipped at the call site when the author is a celebrity.)
func (q *Queries) FanOutPostToFollowers(ctx context.Context, arg FanOutPostToFollowersParams) error {
	_, err := q.db.Exec(ctx, fanOutPostToFollowers, arg.PostID, arg.AuthorID)
	return err
}

const getFeedAfter = `-- name: GetFeedAfter :many
SELECT id, author_id, content, created_at
FROM (
    SELECT p.id, p.author_id, p.content, p.created_at
    FROM timelines t
    JOIN posts p ON p.id = t.post_id
    WHERE t.user_id = $1
    UNION
    SELECT p.id, p.author_id, p.content, p.created_at
    FROM follows f
    JOIN users u ON u.id = f.followee_id
    JOIN posts p ON p.author_id = u.id
    WHERE f.follower_id = $1 AND u.is_celebrity = true
) feed
WHERE (feed.created_at, feed.id) < ($2::timestamptz, $3::bigint)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type GetFeedAfterParams struct {
	UserID          int64              `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// HYBRID feed, next page. Same UNION, with the (created_at, id) keyset cursor
// applied to the MERGED result in the outer query.
func (q *Queries) GetFeedAfter(ctx context.Context, arg GetFeedAfterParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getFeedAfter,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedFirst = `-- name: GetFeedFirst :many
SELECT id, author_id, content, created_at
FROM (
    SELECT p.id, p.author_id, p.content, p.created_at
    FROM timelines t
    JOIN posts p ON p.id = t.post_id
    WHERE t.user_id = $1
    UNION
    SELECT p.id, p.author_id, p.content, p.created_at
    FROM follows f
    JOIN users u ON u.id = f.followee_id
    JOIN posts p ON p.author_id = u.id
    WHERE f.follower_id = $1 AND u.is_celebrity = true
) feed
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type GetFeedFirstParams struct {
	UserID    int64 `json:"user_id"`
	PageLimit int32 `json:"page_limit"`
}

// HYBRID feed, first page. Merges TWO sources with UNION:
//
//	(a) my precomputed timeline — posts pushed by NORMAL users I follow
//	(b) live posts by CELEBRITIES I follow — fetched at read time (not pushed)
//
// UNION (not UNION ALL) de-duplicates if a post appears in both.
func (q *Queries) GetFeedFirst(ctx context.Context, arg GetFeedFirstParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getFeedFirst, arg.UserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
