// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
)

const getIdempotentResponse = `-- name: GetIdempotentResponse :one
SELECT response_status, response_body
FROM idempotency_keys
WHERE user_id = $1 AND key = $2
`

type GetIdempotentResponseParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

type GetIdempotentResponseRow struct {
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   []byte `json:"response_body"`
}

// Has this (user, key) already completed? If so, return the stored response so we
// can replay it instead of doing the work again.
func (q *Queries) GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (GetIdempotentResponseRow, error) {
	row := q.db.QueryRow(ctx, getIdempotentResponse, arg.UserID, arg.Key)
	var i GetIdempotentResponseRow
	err := row.Scan(&i.ResponseStatus, &i.ResponseBody)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (user_id, key, response_status, response_body)
VALUES ($1, $2, $3, $4)
`

type InsertIdempotencyKeyParams struct {
	UserID         int64  `json:"user_id"`
	Key            string `json:"key"`
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   []byte `json:"response_body"`
}

// Record (user, key) -> response. Called INSIDE the post-creation transaction, so
// a concurrent duplicate that already committed this key makes this INSERT fail
// with a unique violation (23505) — rolling back the whole tx, post included.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}
