// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package sqlc

import (
	"context"
)

const countPostLikes = `-- name: CountPostLikes :one
SELECT COUNT(*) FROM likes WHERE post_id = $1
`

// The simple, always-correct count. (Step 3 adds a Redis counter for hot reads.)
func (q *Queries) CountPostLikes(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPostLikes, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const likePost = `-- name: LikePost :one
INSERT INTO likes (user_id, post_id)
VALUES ($1, $2)
ON CONFLICT (user_id, post_id) DO NOTHING
RETURNING post_id
`

type LikePostParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

// Idempotent: ON CONFLICT DO NOTHING means liking twice is a no-op.
// RETURNING post_id tells us whether a NEW like was actually inserted (a row
// comes back) or it was already liked (no row → pgx.ErrNoRows). We'll use that
// distinction later to only bump the Redis counter on a real state change.
func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (int64, error) {
	row := q.db.QueryRow(ctx, likePost, arg.UserID, arg.PostID)
	var post_id int64
	err := row.Scan(&post_id)
	return post_id, err
}

const unlikePost = `-- name: UnlikePost :one
DELETE FROM likes
WHERE user_id = $1 AND post_id = $2
RETURNING post_id
`

type UnlikePostParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

// RETURNING tells us if a like was actually removed (row) vs wasn't there (ErrNoRows).
func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) (int64, error) {
	row := q.db.QueryRow(ctx, unlikePost, arg.UserID, arg.PostID)
	var post_id int64
	err := row.Scan(&post_id)
	return post_id, err
}
