// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Comment struct {
	ID        int64              `json:"id"`
	PostID    int64              `json:"post_id"`
	AuthorID  int64              `json:"author_id"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Follow struct {
	FollowerID int64              `json:"follower_id"`
	FolloweeID int64              `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	UserID         int64              `json:"user_id"`
	Key            string             `json:"key"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Like struct {
	UserID    int64              `json:"user_id"`
	PostID    int64              `json:"post_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type Post struct {
	ID        int64              `json:"id"`
	AuthorID  int64              `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostEmbedding struct {
	PostID    int64           `json:"post_id"`
	Embedding pgvector.Vector `json:"embedding"`
}

type SshKey struct {
	PublicKey string             `json:"public_key"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Timeline struct {
	UserID     int64              `json:"user_id"`
	PostID     int64              `json:"post_id"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsCelebrity  bool               `json:"is_celebrity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
