// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Follow struct {
	FollowerID int64              `json:"follower_id"`
	FolloweeID int64              `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID        int64              `json:"id"`
	AuthorID  int64              `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostEmbedding struct {
	PostID    int64           `json:"post_id"`
	Embedding pgvector.Vector `json:"embedding"`
}

type Timeline struct {
	UserID     int64              `json:"user_id"`
	PostID     int64              `json:"post_id"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
