// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"
)

const fetchUnpublishedOutbox = `-- name: FetchUnpublishedOutbox :many
SELECT id, event_type, payload, created_at, published_at
FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// The relay claims a batch of not-yet-published events, oldest first.
// FOR UPDATE SKIP LOCKED row-locks the claimed rows and skips any a different
// relay already holds — so you can run several relays at once and no two of them
// will ever grab the same event.
func (q *Queries) FetchUnpublishedOutbox(ctx context.Context, batchSize int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, fetchUnpublishedOutbox, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (event_type, payload)
VALUES ($1, $2)
`

type InsertOutboxEventParams struct {
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

// Write a domain event into the outbox. Called in the SAME transaction as the
// state change (e.g. creating a post), so the event and the change commit
// atomically — both or neither. This is the heart of the transactional outbox.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.EventType, arg.Payload)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = NOW() WHERE id = $1
`

// Stamp an event as published, once the relay has handed it to the broker.
func (q *Queries) MarkOutboxPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
