// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    author_id,
    content
)
VALUES ($1, $2)
RETURNING id, author_id, content, created_at
`

type CreatePostParams struct {
	AuthorID int64  `json:"author_id"`
	Content  string `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1 AND author_id = $2
`

type DeletePostParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.AuthorID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, content, created_at
FROM posts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listPostsForEmbedding = `-- name: ListPostsForEmbedding :many
SELECT id, content FROM posts ORDER BY id
`

type ListPostsForEmbeddingRow struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

// Every post's id + content, for the embedding backfill tool. Posts inserted
// directly via SQL (e.g. the eval corpus) never published a post.created event,
// so the worker never embedded them — this lets us embed them after the fact.
func (q *Queries) ListPostsForEmbedding(ctx context.Context) ([]ListPostsForEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listPostsForEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsForEmbeddingRow{}
	for rows.Next() {
		var i ListPostsForEmbeddingRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPostsAfter = `-- name: ListUserPostsAfter :many
SELECT id, author_id, content, created_at
FROM posts
WHERE author_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::bigint)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUserPostsAfterParams struct {
	AuthorID        int64              `json:"author_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// Next page: posts strictly OLDER than the (created_at, id) bookmark.
// The row-value comparison (created_at, id) < (cursor_time, cursor_id) is the
// tuple/tiebreaker we discussed: id breaks ties when two posts share a time.
func (q *Queries) ListUserPostsAfter(ctx context.Context, arg ListUserPostsAfterParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listUserPostsAfter,
		arg.AuthorID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPostsFirst = `-- name: ListUserPostsFirst :many
SELECT id, author_id, content, created_at
FROM posts
WHERE author_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListUserPostsFirstParams struct {
	AuthorID  int64 `json:"author_id"`
	PageLimit int32 `json:"page_limit"`
}

// First page: the newest posts by an author. No cursor yet.
func (q *Queries) ListUserPostsFirst(ctx context.Context, arg ListUserPostsFirstParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listUserPostsFirst, arg.AuthorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
