// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserBySSHKey = `-- name: GetUserBySSHKey :one
SELECT u.id, u.username
FROM ssh_keys k
JOIN users u ON u.id = k.user_id
WHERE k.public_key = $1
`

type GetUserBySSHKeyRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

// Identify the SSH visitor by their public key. ErrNoRows = unregistered → guest.
func (q *Queries) GetUserBySSHKey(ctx context.Context, publicKey string) (GetUserBySSHKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserBySSHKey, publicKey)
	var i GetUserBySSHKeyRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const listRecentPosts = `-- name: ListRecentPosts :many
SELECT p.id, p.author_id, u.username AS author, p.content, p.created_at,
       (SELECT COUNT(*) FROM likes l WHERE l.post_id = p.id) AS like_count
FROM posts p
JOIN users u ON u.id = p.author_id
ORDER BY p.created_at DESC
LIMIT $1
`

type ListRecentPostsRow struct {
	ID        int64              `json:"id"`
	AuthorID  int64              `json:"author_id"`
	Author    string             `json:"author"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LikeCount int64              `json:"like_count"`
}

// The global recent feed the TUI renders: post + author username + live like count.
func (q *Queries) ListRecentPosts(ctx context.Context, resultLimit int32) ([]ListRecentPostsRow, error) {
	rows, err := q.db.Query(ctx, listRecentPosts, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentPostsRow{}
	for rows.Next() {
		var i ListRecentPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerSSHKey = `-- name: RegisterSSHKey :exec
INSERT INTO ssh_keys (public_key, user_id)
VALUES ($1, $2)
ON CONFLICT (public_key) DO UPDATE SET user_id = EXCLUDED.user_id
`

type RegisterSSHKeyParams struct {
	PublicKey string `json:"public_key"`
	UserID    int64  `json:"user_id"`
}

// Claim a public key for a user (so future SSH visits identify them).
// Idempotent re-claim: ON CONFLICT keeps the key pointed at the latest user.
func (q *Queries) RegisterSSHKey(ctx context.Context, arg RegisterSSHKeyParams) error {
	_, err := q.db.Exec(ctx, registerSSHKey, arg.PublicKey, arg.UserID)
	return err
}
