{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newsfeed.fullname" . }}-secrets
  labels:
    {{- include "newsfeed.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASS: {{ .Values.secrets.rabbitmqPass | quote }}
{{- end }}